spring.application.name=minibank


spring.datasource.url=jdbc:mysql://localhost:3306/minibank
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA and Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

#Jwt configuration
jwt.secret=aTf8J9rGh3qLm5Nz7XcVbQeSdFg6KjHyUiOp2WsE
jwt.expiration=432000